import blog_post from '../assets/img/blog_post.jpg';
export const blog_posts = [
  {
    _id: 1,
    name: "RefugeCraft1",
    image: blog_post,
    desc: "The Child Rights Advocacy Coalition Bangladesh (CRAC, B) orchestrated a Mock Universal Periodic Review (UPR) for children on February 28, 2024, at the CIRDAP International Conference Centre in Dhaka. The primary goal was to enlighten children about the recommendations received during the 4th Cycle of Universal Periodic Review (UPR) on child rights, conducted in November 2023. Out of the 300 recommendations received by the Government of Bangladesh, approximately 90 were related to children. The event aimed to reaffirm the necessity for the government to accept and implement these recommendations, solicit the children's perspectives on these recommendations, adaptation and implementation plans, and ensure their effective participation in relevant stages of UPR follow-up processes.",
    category:'Publications',
    date:'25/5/24',
  },
  {
    _id: 2,
    name: "RefugeCraft2",
    image: blog_post,
    desc: "The Child Rights Advocacy Coalition Bangladesh (CRAC, B) orchestrated a Mock Universal Periodic Review (UPR) for children on February 28, 2024, at the CIRDAP International Conference Centre in Dhaka. The primary goal was to enlighten children about the recommendations received during the 4th Cycle of Universal Periodic Review (UPR) on child rights, conducted in November 2023. Out of the 300 recommendations received by the Government of Bangladesh, approximately 90 were related to children. The event aimed to reaffirm the necessity for the government to accept and implement these recommendations, solicit the children's perspectives on these recommendations, adaptation and implementation plans, and ensure their effective participation in relevant stages of UPR follow-up processes.",
    category:'Publications',
    date:'25/5/24',
  },
  {
    _id: 3,
    name: "RefugeCraft3",
    image: blog_post,
    desc: "The Child Rights Advocacy Coalition Bangladesh (CRAC, B) orchestrated a Mock Universal Periodic Review (UPR) for children on February 28, 2024, at the CIRDAP International Conference Centre in Dhaka. The primary goal was to enlighten children about the recommendations received during the 4th Cycle of Universal Periodic Review (UPR) on child rights, conducted in November 2023. Out of the 300 recommendations received by the Government of Bangladesh, approximately 90 were related to children. The event aimed to reaffirm the necessity for the government to accept and implement these recommendations, solicit the children's perspectives on these recommendations, adaptation and implementation plans, and ensure their effective participation in relevant stages of UPR follow-up processes.",
    category:'Publications',
    date:'25/5/24',
  },
  {
    _id: 4,
    name: "RefugeCraft4",
    image: blog_post,
    desc: "The Child Rights Advocacy Coalition Bangladesh (CRAC, B) orchestrated a Mock Universal Periodic Review (UPR) for children on February 28, 2024, at the CIRDAP International Conference Centre in Dhaka. The primary goal was to enlighten children about the recommendations received during the 4th Cycle of Universal Periodic Review (UPR) on child rights, conducted in November 2023. Out of the 300 recommendations received by the Government of Bangladesh, approximately 90 were related to children. The event aimed to reaffirm the necessity for the government to accept and implement these recommendations, solicit the children's perspectives on these recommendations, adaptation and implementation plans, and ensure their effective participation in relevant stages of UPR follow-up processes.",
    category:'Publications',
    date:'25/5/24',
  },
  {
    _id: 5,
    name: "RefugeCraft5",
    image: blog_post,
    desc: "The Child Rights Advocacy Coalition Bangladesh (CRAC, B) orchestrated a Mock Universal Periodic Review (UPR) for children on February 28, 2024, at the CIRDAP International Conference Centre in Dhaka. The primary goal was to enlighten children about the recommendations received during the 4th Cycle of Universal Periodic Review (UPR) on child rights, conducted in November 2023. Out of the 300 recommendations received by the Government of Bangladesh, approximately 90 were related to children. The event aimed to reaffirm the necessity for the government to accept and implement these recommendations, solicit the children's perspectives on these recommendations, adaptation and implementation plans, and ensure their effective participation in relevant stages of UPR follow-up processes.",
    category:'Publications',
    date:'25/5/24',
  },
  {
    _id: 6,
    name: "RefugeCraft6",
    image: blog_post,
    desc: "The Child Rights Advocacy Coalition Bangladesh (CRAC, B) orchestrated a Mock Universal Periodic Review (UPR) for children on February 28, 2024, at the CIRDAP International Conference Centre in Dhaka. The primary goal was to enlighten children about the recommendations received during the 4th Cycle of Universal Periodic Review (UPR) on child rights, conducted in November 2023. Out of the 300 recommendations received by the Government of Bangladesh, approximately 90 were related to children. The event aimed to reaffirm the necessity for the government to accept and implement these recommendations, solicit the children's perspectives on these recommendations, adaptation and implementation plans, and ensure their effective participation in relevant stages of UPR follow-up processes.",
    category:'Publications',
    date:'25/5/24',
  },
  {
    _id: 7,
    name: "RefugeCraft7",
    image: blog_post,
    desc: "The Child Rights Advocacy Coalition Bangladesh (CRAC, B) orchestrated a Mock Universal Periodic Review (UPR) for children on February 28, 2024, at the CIRDAP International Conference Centre in Dhaka. The primary goal was to enlighten children about the recommendations received during the 4th Cycle of Universal Periodic Review (UPR) on child rights, conducted in November 2023. Out of the 300 recommendations received by the Government of Bangladesh, approximately 90 were related to children. The event aimed to reaffirm the necessity for the government to accept and implement these recommendations, solicit the children's perspectives on these recommendations, adaptation and implementation plans, and ensure their effective participation in relevant stages of UPR follow-up processes.",
    category:'Publications',
    date:'25/5/24',
  },
  {
    _id: 8,
    name: "RefugeCraft8",
    image: blog_post,
    desc: "The Child Rights Advocacy Coalition Bangladesh (CRAC, B) orchestrated a Mock Universal Periodic Review (UPR) for children on February 28, 2024, at the CIRDAP International Conference Centre in Dhaka. The primary goal was to enlighten children about the recommendations received during the 4th Cycle of Universal Periodic Review (UPR) on child rights, conducted in November 2023. Out of the 300 recommendations received by the Government of Bangladesh, approximately 90 were related to children. The event aimed to reaffirm the necessity for the government to accept and implement these recommendations, solicit the children's perspectives on these recommendations, adaptation and implementation plans, and ensure their effective participation in relevant stages of UPR follow-up processes.",
    category:'Publications',
    date:'25/5/24',
  },
];
